schema_version: 20180708

name: micromata/dokumentor
version: 0.0.1
runtime: java

cmd: de.micromata.dokumentor.QRGen::create
timeout: 30

triggers:
  - name: t1
    type: http
    source: /dokumentor
